spring.application.name=mycoolapp
management.endpoints.web.exposure.include=*
management.info.env.enabled=true

info.app.name=my app
info.app.description= my app description
info.app.version=1.0.0

# Custom properties ---

coach.name = Mickey Mouse
team.name = The Mouse Club

# Server configurations

server.port= 7070
server.servlet.context-path=/mycoolapp