spring.application.name=mycoolapp
management.endpoints.web.exposure.include=health,info,metrics
management.info.env.enabled=true

info.app.name=my app
info.app.description= my app description
info.app.version=1.0.0